<div class="form-row">
    <div class="col-md-12">
    <div class="card mt-3">
            <div class="card-header">
                <h3 class="">Reporte de Movimientos por Categoria</h3>
            </div>
            <div class="card-body" id="">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Selección del Periodo:</label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" name="fechas" id="fechas" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row" style="display:none;" id="divGraficos">
            <div class="col-md-6">
                <div class="form-row">
                    <div class="col-md-12 text-center">
                        <div id="tortaIngresos" style="height: 500px;"></div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-12 text-center">
                        <h3 id="saldoIngresos"></h3>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-row">
                    <div class="col-md-12 text-center">
                        <div id="tortaGastos" style="height: 500px;"></div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-12 text-center">
                        <h3 id="saldoGastos"></h3>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <h3 class="">Movimientos en Periodo Seleccionado</h3>
            </div>
            <div class="card-body" id="divMovPeriodo">
                <table id="tablaMovimientosPeriodo" class="table table-hover">
                    <thead>
                        <tr class="">
                            <th class="text-center">Fecha</th>
                            <th class="text-center">Motivo</th>
                            <th class="text-center">Detalle</th>
                            <th class="text-center">Valor</th>
                        </tr>
                    </thead>
                    <tbody id="bodyMovimientosPeriodo">
                    
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>
<script>

var arrMovimientosJSON = <?= $arrMovimientosJSON ?>;

$(document).ready(function (e) {
    $('input[name="fechas"]').daterangepicker({
        locale: {
            format: 'DD/MM/YYYY',
            applyLabel: "Aplicar",
            cancelLabel: "Cancelar",
            fromLabel: "Desde",
            toLabel: "Hasta",
            customRangeLabel: "Personalizado",
            daysOfWeek: [
                "Dom",
                "Lun",
                "Mar",
                "Mie",
                "Jue",
                "Vie",
                "Sab"
            ],
            monthNames: [
                "Enero",
                "Febrero",
                "Marzo",
                "Abril",
                "Mayo",
                "Junio",
                "Julio",
                "Agosto",
                "Septiembre",
                "Octubre",
                "Noviembre",
                "Diciembre"
            ]
        },
        // minDate: , //La fecha minima de movimientos
        // maxDate: , //fecha maxima de movimientos
        ranges: {
            'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Últimos 7 Días': [moment().subtract(6, 'days'), moment()],
            'Últimos 30 Días': [moment().subtract(29, 'days'), moment()],
            'Este Mes': [moment().startOf('month'), moment().endOf('month')],
            'Mes Anterior': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        alwaysShowCalendars: true,
    });

    
    

});

    var fechaInicialSelec = '';
    var fechaFinalSelec = '';
    var arrMovEnPeriodo = [];
    var arrMovEnPeriodo = [];
    var cantidadesMovIngresos = {};
    var cantidadesMovGastos = {};
    var cantidadesMovTotal = {};
    //Dibujo de graficos
    //https://developers.google.com/chart/interactive/docs/gallery/piechart

    google.charts.load('current', {'packages':['corechart']});

    /**
     * Detecta cuando el usuario realiza la seleccion de un periodo.
     */
    $('#fechas').on('apply.daterangepicker', function(ev, picker) {
        procesarMovimientosEnElPeriodo(picker.startDate, picker.endDate)
        dibujarTablaMovimientosPeriodo();
        analisarResultadosParaGrafico();
        $('#divGraficos').fadeIn(500);
        dibujarGraficoTortaIngresos();
        dibujarGraficoTortaGastos();
    });

/**
 * Esta funcion crea el arreglo global que mantiene los movimientos que
 * cumplen con las fechas seleccionadas.
 *
 * @return void
 */
function procesarMovimientosEnElPeriodo(fechaInicial, fechaFinal){
    arrMovEnPeriodo = [];
    for (var i = 0; i < arrMovimientosJSON.length; i++)
    {
        var movimiento = arrMovimientosJSON[i];
        var fechaMov = moment(movimiento.fecha.substring(0, 10), "DD/MM/YYYY");
        
        if ((fechaInicial.diff(fechaMov) <= 0) && (fechaFinal.diff(fechaMov) >= 0)){
            arrMovEnPeriodo.push(movimiento);
        }
    }
}

/**
 * Funcion que se encarga de dibujar la tabla de movimientos en el periodo seleccionado.
 */
function dibujarTablaMovimientosPeriodo(){
    $('#bodyMovimientosPeriodo').find('tr').remove();

    for (var i = 0; i < arrMovimientosJSON.length; i++)
    {
        var movimiento = arrMovimientosJSON[i];
        procesarNuevaFilaEnTablaHTML(movimiento);
    }
}

function procesarNuevaFilaEnTablaHTML(movimiento){
    var body = document.getElementById("bodyMovimientosPeriodo");
    var row = body.insertRow();
    
    var fecha = row.insertCell(0);
    var motivo = row.insertCell(1);
    var detalle = row.insertCell(2);
    var valor = row.insertCell(3);
    
    fecha.innerHTML = movimiento.fecha.substring(0,16);
    motivo.innerHTML = movimiento.motivoMovimiento.descripcion;
    detalle.innerHTML = movimiento.descripcion;
    valor.innerHTML = movimiento.valor;
    
    if (movimiento.motivoMovimiento.categoriaMovimiento != ''
        && movimiento.motivoMovimiento.categoriaMovimiento.tipoMovimiento != ''){
        valor.style.color = movimiento.motivoMovimiento.categoriaMovimiento.tipoMovimiento.color;
    }
}

function dibujarTablaMovimientosPorCategoria(descSeleccionada){
    $('#bodyMovimientosPeriodo').find('tr').remove();

    for (var i = 0; i < arrMovEnPeriodo.length; i++)
    {
        var movimiento = arrMovEnPeriodo[i];
        if (movimiento.motivoMovimiento.categoriaMovimiento != ''){
            var categoriaDesc = movimiento.motivoMovimiento.categoriaMovimiento.descripcion;

            if (descSeleccionada == categoriaDesc){
                procesarNuevaFilaEnTablaHTML(movimiento);
            }
        }
    }
}

/**
* Funcion para guardar los datos de movimientos dentro del periodo en el arreglo correspondinete.
* Esta funcion es para mostrar las sumas totales de pesos tanto para ingresos como para gastos
*/
function procesarCargaDeArrDeDatos(arrCantMov, movimiento){
    if (movimiento.motivoMovimiento.categoriaMovimiento != ''){
        var descCategoria = movimiento.motivoMovimiento.categoriaMovimiento.descripcion;

        if (arrCantMov.hasOwnProperty(descCategoria)){
            arrCantMov[descCategoria] += parseFloat(movimiento.valor);
        }else{
            arrCantMov[descCategoria] = parseFloat(movimiento.valor);
        }
    }
}

/**
* Funcion para guardar los datos de movimientos dentro del periodo en el arreglo correspondinete.
* Esta funcion es para mostrar las sumas totales haciendo una division entre ingresos y gastos.
*/
function procesarCargaDeArrDeIngresosGastos(arrCantMov, movimiento){
    if (movimiento.motivoMovimiento.categoriaMovimiento != ''){
        var descCategoria = movimiento.motivoMovimiento.categoriaMovimiento.descripcion;

        if (arrCantMov.hasOwnProperty(descCategoria)){
            arrCantMov[descCategoria] += Math.abs(movimiento.valor);
        }else{
            arrCantMov[descCategoria] = Math.abs(movimiento.valor);
        }
    }
}

/**
 * Funcion que determina cuales son los movimientos que cumplen con el
 * periodo de tiempo seleccionado. A su vez hace una division en ingresos o gastos.
 *
 * @return void
 */
function analisarResultadosParaGrafico(){
    cantidadesMovIngresos = {};
    cantidadesMovGastos = {};
    for (var i = 0; i < arrMovEnPeriodo.length; i++){
        var movimiento = arrMovEnPeriodo[i];
        
        if (movimiento.motivoMovimiento.categoriaMovimiento != '' 
            && movimiento.motivoMovimiento.categoriaMovimiento.tipoMovimiento != ''){
            if (movimiento.motivoMovimiento.categoriaMovimiento.tipoMovimiento.id == '1'){
                //Ingresos
                procesarCargaDeArrDeDatos(cantidadesMovIngresos, movimiento);
            }else{
                //Gastos
                procesarCargaDeArrDeIngresosGastos(cantidadesMovGastos, movimiento);
            }
        }
        
    }
}

/**
* Procesa el dibujo de un grafico de torta
*/
function procesarDibujarGraficoTorta(arrMovimientos, arrDatosGrafico, tituloGrafico, idDivGrafico){
    Object.keys(arrMovimientos).forEach(function(key){
        var elemento = [key, Math.abs(arrMovimientos[key])];

        arrDatosGrafico.push(elemento);
    });

    var data = google.visualization.arrayToDataTable(arrDatosGrafico);

    var options = {
        title: tituloGrafico,
        legend: {position: 'none'}
    };

    var chart = new google.visualization.PieChart(document.getElementById(idDivGrafico));

    function selectHandler() {
        var selectedItem = chart.getSelection()[0];
        if (selectedItem) {
            var topping = data.getValue(selectedItem.row, 0);
            dibujarTablaMovimientosPorCategoria (topping);
        }else{
            dibujarTablaMovimientosPeriodo();
        }
    }
    
    google.visualization.events.addListener(chart, 'select', selectHandler);

    chart.draw(data, options);
}

/**
 * Funcion que cuenta el total de los valores de cada una de la
 * "porcion" de torta del grafico.
 */
function contarTotalPesosArr(arrCantidades){
    var total = 0;

    Object.keys(arrCantidades).forEach(function(key){
        total += Math.abs(arrCantidades[key]);
    });

    return total;
}

/**
 * Funcion que calcula el saldo final de los movimientos.
 * Hace la resta entre los ingresos y gastos. Si alguno de ellos
 * no se encuentra definido, lo asume como 0.
 */
function calcularSaldoTotal(arrMovEnPeriodo){
    var totalIngreso = 0;
    var totalGasto = 0;
    
    if (arrMovEnPeriodo.hasOwnProperty('Ingreso')){
        totalIngreso = arrMovEnPeriodo['Ingreso'];
    }

    if (arrMovEnPeriodo.hasOwnProperty('Gasto')){
        totalGasto = arrMovEnPeriodo['Gasto'];
    }

    var total = parseFloat(totalIngreso) - parseFloat(totalGasto);

    return total;
}

/**
 * Funcion que se encarga de dibujar el grafico de torta de los movimientos totales
 * (ingresos + gastos)
 *
 * @return void
 */
function dibujarGraficoTotal(){
    var arrDatos = [
        ['Tipo de Movimiento', 'Pesos']
    ];

    var total = calcularSaldoTotal(cantidadesMovTotal);
    document.getElementById('saldoTotal').innerHTML = 'Saldo: $'+total.toFixed(2);
    procesarDibujarGraficoTorta(cantidadesMovTotal, arrDatos, 'Pesos $AR por Tipo de Movimiento', 'tortaTotal');
}

/**
 * Funcion que se encarga de dibujar el grafico de torta de los ingresos
 *
 * @return void
 */
function dibujarGraficoTortaIngresos() {
    var arrDatos = [
        ['Tipo de Movimiento', 'Pesos']
    ];

    $('#tortaIngresosGasto').fadeIn(500);
    $('#saldoTipoMov').fadeIn(500);

    var totalIngresos = contarTotalPesosArr(cantidadesMovIngresos);

    document.getElementById('saldoIngresos').innerHTML = 'Total: $'+totalIngresos.toFixed(2);
    procesarDibujarGraficoTorta(cantidadesMovIngresos, arrDatos, 'Pesos $AR por Tipo de Ingresos', 'tortaIngresos');
}

/**
 * Funcion que se encarga de dibujar el grafico de torta de los gastos
 *
 * @return void
 */
function dibujarGraficoTortaGastos() {
    var arrDatos = [
        ['Tipo de Movimiento', 'Pesos']
    ];
    $('#tortaIngresosGasto').fadeIn(500);
    $('#saldoTipoMov').fadeIn(500);
    
    var totalGastos = contarTotalPesosArr(cantidadesMovGastos);
    
    document.getElementById('saldoGastos').innerHTML = 'Total: $'+totalGastos.toFixed(2);
    procesarDibujarGraficoTorta(cantidadesMovGastos, arrDatos, 'Pesos $AR por Tipo de Gastos', 'tortaGastos');
}

</script>