<div class="form-row">
    <div class="col-md-12">
    <div class="card mt-3">
            <div class="card-header">
                <h3 class="">Remporte de Compras Con Tarjeta de Débito</h3>
            </div>
            <div class="card-body" id="">
                <div class="form-row">
                    <div class="col-md-2">
                        <label for="">Selección del Periodo:</label>
                    </div>
                    <div class="col-md-3">
                        <input type="text" name="fechas" id="fechas" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row" style="display:none;" id="divGraficos">
            <div class="col-md-6">
                <div id="tortaGastos" style="height: 500px;"></div>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <h3 class="">Movimientos en Periodo Seleccionado</h3>
            </div>
            <div class="card-body" id="divMovPeriodo">
                <table id="tablaMovimientosPeriodo" class="table table-hover">
                    <thead>
                        <tr class="">
                            <th class="text-center">Fecha</th>
                            <th class="text-center">Local</th>
                            <th class="text-center">Tarjeta</th>
                            <th class="text-center">Valor</th>
                        </tr>
                    </thead>
                    <tbody id="bodyMovimientosPeriodo">
                    
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>
<script>

var arrMovimientosJSON = <?= $arrMovimientosJSON ?>;

$(document).ready(function (e) {
    $('input[name="fechas"]').daterangepicker({
        locale: {
            format: 'DD/MM/YYYY',
            applyLabel: "Aplicar",
            cancelLabel: "Cancelar",
            fromLabel: "Desde",
            toLabel: "Hasta",
            customRangeLabel: "Personalizado",
            daysOfWeek: [
                "Dom",
                "Lun",
                "Mar",
                "Mie",
                "Jue",
                "Vie",
                "Sab"
            ],
            monthNames: [
                "Enero",
                "Febrero",
                "Marzo",
                "Abril",
                "Mayo",
                "Junio",
                "Julio",
                "Agosto",
                "Septiembre",
                "Octubre",
                "Noviembre",
                "Diciembre"
            ]
        },
        // minDate: , //La fecha minima de movimientos
        // maxDate: , //fecha maxima de movimientos
        ranges: {
            'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Últimos 7 Días': [moment().subtract(6, 'days'), moment()],
            'Últimos 30 Días': [moment().subtract(29, 'days'), moment()],
            'Este Mes': [moment().startOf('month'), moment().endOf('month')],
            'Mes Anterior': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        alwaysShowCalendars: true,
    });

    
    

});

    var fechaInicialSelec = '';
    var fechaFinalSelec = '';
    var arrMovEnPeriodo = [];
    var arrMovEnPeriodo = [];
    var cantidadesMovIngresos = {};
    var cantidadesMovGastos = {};
    //Dibujo de graficos
    //https://developers.google.com/chart/interactive/docs/gallery/piechart

    google.charts.load('current', {'packages':['corechart']});

$('#fechas').on('apply.daterangepicker', function(ev, picker) {
    procesarMovimientosEnElPeriodo(picker.startDate, picker.endDate)
    dibujarTablaMovimientosPeriodo();
    analisarResultadosParaGrafico();
    $('#divGraficos').fadeIn(500);
    dibujarGraficoTortaGastos();
});

/**
 * Esta funcion crea el arreglo global que mantiene los movimientos que
 * cumplen con las fechas seleccionadas.
 *
 * @return void
 */
function procesarMovimientosEnElPeriodo(fechaInicial, fechaFinal){
    arrMovEnPeriodo = [];
    for (var i = 0; i < arrMovimientosJSON.length; i++)
    {
        var movimiento = arrMovimientosJSON[i];
        var fechaMov = moment(movimiento.fecha.substring(0, 10), "DD/MM/YYYY");
        
        if ((fechaInicial.diff(fechaMov) <= 0) && (fechaFinal.diff(fechaMov) >= 0)){
            arrMovEnPeriodo.push(movimiento);
        }
    }
}

function dibujarTablaMovimientosPeriodo(){
    $('#bodyMovimientosPeriodo').find('tr').remove();

    for (var i = 0; i < arrMovEnPeriodo.length; i++)
    {
        var movimiento = arrMovEnPeriodo[i];
        
        procesarNuevaFilaEnTablaHTML(movimiento);
    }
}

function procesarNuevaFilaEnTablaHTML(movimiento){
    var body = document.getElementById("bodyMovimientosPeriodo");
    var row = body.insertRow();

    var fecha = row.insertCell(0);
    fecha.classList.add("text-center");
    var local = row.insertCell(1);
    local.classList.add("text-center");
    var tarjeta = row.insertCell(2);
    tarjeta.classList.add("text-center");
    var valor = row.insertCell(3);
    valor.classList.add("text-center");

    fecha.innerHTML = movimiento.fecha.substring(0,16);

    var arrString = movimiento.descripcion.split(' - ');

    if (arrString.length > 1){
        local.innerHTML = arrString[0];
        tarjeta.innerHTML = arrString[1];
    }else{
        local.innerHTML = arrString[0];
        tarjeta.innerHTML = '';
    }

    valor.innerHTML = movimiento.valor;

    if (parseFloat(movimiento.valor) > 0){
        valor.style.color = 'green';
    }else{
        valor.style.color = 'red';
    }
}

function dibujarTablaMovimientosPorNegocio(descSeleccionada){
    $('#bodyMovimientosPeriodo').find('tr').remove();

    for (var i = 0; i < arrMovEnPeriodo.length; i++)
    {
        var movimiento = arrMovEnPeriodo[i];
        var nombreNegocio = recuperarNombreNegocio(movimiento.descripcion);

        if (descSeleccionada == nombreNegocio){
            procesarNuevaFilaEnTablaHTML(movimiento);
        }
        
    }
}

function recuperarNombreNegocio(descMotivo){
    var arrString = descMotivo.split(' - ');
    
    if (arrString.length > 1){
        return arrString[0];
    }

    return '';
}

/**
* Funcion para guardar los datos de movimientos dentro del periodo en los arreglos correspondinetes
* Esta funcion es para mostrar las sumas totales de pesos
* tanto para ingresos como para gastos
*/
function procesarCargaDeArrDeDatos(arrCantMov, movimiento){
    var descMotivo = movimiento.motivoMovimiento.descripcion;

    var descNegocio = recuperarNombreNegocio(movimiento.descripcion);
    if (descNegocio != '' && arrCantMov.hasOwnProperty(descNegocio)){
        arrCantMov[descNegocio] += parseFloat(movimiento.valor);
    }else if (descNegocio != ''){
        arrCantMov[descNegocio] = parseFloat(movimiento.valor);
    }
}

/**
 * Funcion que determina cuales son los movimientos que cumplen con el
 * periodo de tiempo seleccionado. A su vez hace una division en ingresos o gastos.
 *
 * @return void
 */
function analisarResultadosParaGrafico(){
    cantidadesMovIngresos = {};
    cantidadesMovGastos = {}
    for (var i = 0; i < arrMovEnPeriodo.length; i++){
        var movimiento = arrMovEnPeriodo[i];
        
        if (movimiento.motivoMovimiento.categoriaMovimiento != '' 
            && movimiento.motivoMovimiento.categoriaMovimiento.tipoMovimiento != ''){
            if (movimiento.motivoMovimiento.categoriaMovimiento.tipoMovimiento.id == '1'){
                //Ingresos
                procesarCargaDeArrDeDatos(cantidadesMovIngresos, movimiento);
            }else{
                //Gastos
                procesarCargaDeArrDeDatos(cantidadesMovGastos, movimiento);
            }
        }
        
    }
}

/**
* Procesa el dibujo de un grafico de torta
*/
function procesarDibujarGraficoTorta(arrMovimientos, arrDatosGrafico, tituloGrafico, idDivGrafico){
    Object.keys(arrMovimientos).forEach(function(key){
        var elemento = [key, Math.abs(arrMovimientos[key])];

        arrDatosGrafico.push(elemento);
    });

    var data = google.visualization.arrayToDataTable(arrDatosGrafico);

    var options = {
        title: tituloGrafico,
        legend: {position: 'none'}
    };

    var chart = new google.visualization.PieChart(document.getElementById(idDivGrafico));
    
    function selectHandler() {
        var selectedItem = chart.getSelection()[0];
        if (selectedItem) {
            var topping = data.getValue(selectedItem.row, 0);
            dibujarTablaMovimientosPorNegocio(topping);
        }else{
            dibujarTablaMovimientosPeriodo();
        }
    }

    
    google.visualization.events.addListener(chart, 'select', selectHandler);
    
    chart.draw(data, options);
}


function dibujarGraficoTortaGastos() {
    var arrDatos = [
        ['Tipo de Movimiento', 'Pesos']
    ];

    procesarDibujarGraficoTorta(cantidadesMovGastos, arrDatos, 'Pesos $AR por Tipo de Gastos', 'tortaGastos');
    
}

</script>