<div class="form-row">
    <div class="col-md-12">
        <div class="card mt-3">
            <div class="card-header">
                <h3 class="">Ejemplo de movimiento</h3>
            </div>
            <div class="card-body">
                <table id="tablaMotivos" class="footable table table-stripped toggle-arrow-tiny no-borders">
                    <thead>
                        <tr>
                            <th class="text-center">Fecha</th>
                            <th class="text-center">Motivo</th>
                            <th class="text-center">Detalle</th>
                            <th class="text-center">Valor</th>
                        </tr>
                    </thead>
                    <tbody id="bodyMotivos">
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <h3 class="">Asignación de Categoria</h3>
            </div>
            <div class="card-body">
                <form method="post" id="formMotivoMovimiento" name="formMotivoMovimiento">
                    <div class="form-row">
                        <div class="col-md-2">
                            <label for="">Descripción:</label>
                        </div>
                        <div class="col-md-3">
                            <input type="text" id="" name="" class="form-control" disabled="true" value="<?= $MotivoMovimiento->getDescripcion()?>">
                        </div>
                        <div class="col-md-1 offset-1">
                            <label for="">Categoria:</label>
                        </div>
                        <div class="col-md-3">
                            <select id="selectIdCategoriaMov" name="selectIdCategoriaMov" class="form-control">
                                                    
                            </select>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<script>
    var arrCategoriaMovimientoJSON = <?= $arrCategoriaMovimientoJSON; ?>;

    function dibujarSelectCategorias(){
        $('#selectIdCategoriaMov')
            .find('option')
            .remove();
        $('#selectIdCategoriaMov')
            .append($("<option></option>")
                .attr("value", -1)
                .text('-- Seleccione --'));
        
        for (var i = 0; i < arrCategoriaMovimientoJSON.length; i++){
            var categoria = arrCategoriaMovimientoJSON[i];
            var option = $("<option></option>")
                                .attr("value", categoria.id)
                                .text(categoria.descripcion);
            $('#selectIdCategoriaMov').append(option);
        }
    }

    $(document).ready(function (e) {
        dibujarSelectCategorias();
    });
</script>