<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url("conf/motivosMovimiento", ["action" => "listarMotivos"]) ?>">Motivo Movimientos</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url("conf/categoriaMovimiento", ["action" => "listarCategorias"]) ?>">Categoria Movimientos</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url("conf/tiposMovimiento", ["action" => "listarTiposMovimiento"]) ?>">Tipos de Movimientos</a>
    </div>
</div>
